### ISSUE TITLE
Photo speaker manquante

### ISSUE THREAD

**Issue by finalspy** [CodeursEnSeine/codeursenseine-new#24]
Sur le meetup stream processing de mercredi soir 21/10 il manquela photo spearker.
![image](https://user-images.githubusercontent.com/413502/96412724-d7794300-11ea-11eb-9ac4-83f0e7cce99f.png)

dans le code on a : 
`<MeetupSpeaker speaker={{
  name: "Nicolas Frankel",
  avatar: "https://pbs.twimg.com/profile_images/1063110424306929664/9pYrPAp6_400x400.jpg",
  twitter: "nicolas_frankel",
  bio: `
Nicolas Frankel ...
`
}} />`

J'ai merdé un truc ou bien ?

**Comment by yoannfleurydev** [comment]
I'm closing this one as it is a browser configuration that blocks images from Twitter as it is considered a tracker.

If you are on Firefox, the `Strict` configuration of **Enhanced Tracking Protection** is causing this behavior.

<img width="690" alt="image" src="https://user-images.githubusercontent.com/3920615/96443064-53d04e00-120c-11eb-895d-2ea17537f90e.png">
